### PR TITLE
Bower script

### PR DESCRIPTION
**Pull request by dardalan**

### CODE REVIEW

**Comment by konstantinzolotarev** [comment]
@dardalan Thank you very much for PR. Could you please remove changes from 
`.package.json.swp` `bower.json` and `package.json` they are related to another repo.

**Comment by konstantinzolotarev** [comment]
@dardalan Anyway I'd ask you to set me as author for this hook. Even in your repo according to MIT Licence.

**Comment by dardalan** [comment]
hey, it was my first fork sorry, i will set up you as a author)

2015-12-27 5:13 GMT+02:00 Konstantin Zolotarev <notifications@github.com>:

**Comment by konstantinzolotarev** [comment]
@dardalan You could just add author and contributor Like this.
```javascript

"license": "MIT",
  "author": {
    "name": "Eugene Obrezkov",
    "email": "ghaiklor@gmail.com",
    "url": "http://ghaiklor.com/"
  },
  "contributors": [
    {
      "name": "Travis Webb",
      "url": "https://github.com/tjwebb"
    },
    {
      "name": "Konstantin Zolotarev",
      "url": "https://github.com/konstantinzolotarev"
    }
    {
      "name": "Dmitriy Akulich",
      "url": "https://github.com/IncoCode"
    }
  ],
```

**Pull request closed without merging**
